### PR TITLE
Fix: ReferenceSample Listing Table Multi choice field issue

### PR DESCRIPTION
**Pull request by Bugerman58**
## Description of the issue/feature this PR addresses

_...with description from @toropok_ 

References samples app.listing multi choice field doesn’t display checkboxes properly.

When user adds Reference sample to the worksheet using `AddControlView` or `AddBlankView` - the system offers the choice of particular ReferenceSamples.

But checkboxes of Multichoice field aren’t selected, the object which comes to the browser contains information that the AnalysesService should be in selected state via selected field for each item.

That happens because React component doesn’t aware how to handle this selected field

## Current behavior before PR

not selected

## Desired behavior after PR is merged

selected

--
I confirm I have tested the PR thoroughly and coded it according to [PEP8][1]
standards.

[1]: https://www.python.org/dev/peps/pep-0008

### CODE REVIEW

**Comment by Bugerman58** [comment]
This micro PR needed for this code:
[senaite.core - referencesamples.py](https://github.com/senaite/senaite.core/blob/2.x/src/bika/lims/browser/worksheet/views/referencesamples.py#L199)
```python
choices.append({
    "ResultValue": uid,
    "ResultText": title,
    "selected": selected,
})
```
or I can correct the `folderitem` method in the same file that would solved problem with selected checkboxes items?

**Comment by xispa** [comment]
> This micro PR needed for this code:
> [senaite.core - referencesamples.py](https://github.com/senaite/senaite.core/blob/2.x/src/bika/lims/browser/worksheet/views/referencesamples.py#L199)
> ```python
> choices.append({
>     "ResultValue": uid,
>     "ResultText": title,
>     "selected": selected,
> })
> ```
> or I can correct the `folderitem` method in the same file that would solved problem with selected checkboxes items?

Hi @Bugerman58 , leave it here for now. It seems clear we have an inconsistency here in the way we flag the checkbox as selected in this component. 

Will review this PR asap. I want to be sure why this was done this way, specially because there are other add-ons like senaite.ast that use it.

**Comment by Bugerman58** [comment]
@xispa , thanks for the feedback

**Review by xispa — CHANGES_REQUESTED** [review]
Note the attribute `value` is a list containing the checkbox items that have to be ticked (selected).

While for `MultiChoice` component we render a list of checkbox elements, for components like `MultiSelect` we render a `select` html element for each value (see https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/MultiSelect.coffee#L128):

```html
<select value='1'>
   <option value='1'>Compatible</option>
   <option value='2'>Incompatible</option>
   <option value='3'>Unknown</option>
</select>
<select value='2'>
   <option value='1'>Compatible</option>
   <option value='2'>Incompatible</option>
   <option value='3'>Unknown</option>
</select>
```

That looks similar to this:

Captura de 2024-04-16 12-41-14

`MultiChoice`, however, is made of a list of `checkbox` elements that are not *wrapped* inside any another select-like element. Thus, we need to handle the logic to "select"/"unselect" elements manually in our component, as we do here with `selected = value.toString() in values`. 

It makes sense to follow exactly the same behavior regardless of the component type, so one can eventually render a `MultiChoice` or `MultiSelect` component with exactly same input and the output result would be consistent. This is the reason why `values` is a list containing the elements to remain selected when the component is rendered. 

Better stick to the default behavior rather than using `option.selected`. You can simply set the *default* value(s) for the field `SupportedServices` here: https://github.com/senaite/senaite.core/blob/2.x/src/bika/lims/browser/worksheet/views/referencesamples.py#L252

Something like this should work:

```python
# set the available services for selection
item["choices"]["SupportedServices"] = choices

# set the services that are selected by default
selected = []
for choice in supported_services_choices:
    if choice.get("selected", False):
        selected.append(choice)
item["SupportedServices"] = selected
```

In fact, what we should do instead is to remove remove these `selected = props.selected or @is_selected()` spread in React components that don't use them like `MultiSelect` (assigned [here](https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/TableCell.coffee#L784) , but not used at all when rendering the options [here](https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/MultiSelect.coffee#L128)). They are really confusing. Same with `MultiValue` component, etc.

**Comment by Bugerman58** [comment]
> Something like this should work: ...

indeed, as a hotfix we added an additional element containing the selected values after line 252 in the `referencesamples.py`, but we used existing method int the class `get_assigned_services_uids`:
```python
item["SupportedServices"] = self.get_assigned_services_uids()
```
and it helped us.

**Comment by Bugerman58** [comment]
> In fact, what we should do instead is to remove remove these selected = props.selected or @is_selected() spread in React components that don't use them like MultiSelect (assigned [here](https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/TableCell.coffee#L784) , but not used at all when rendering the options [here](https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/MultiSelect.coffee#L128)). They are really confusing. Same with MultiValue component, etc.

From what I gather from your suggestion and after analyzing the code, it seems that we need to completely remove `selected = props.selected or @is_selected()` and `selected={selected}` in the `TableCell.coffee` component for each field type:
* CalculatedField
* NumericField
* StringField
* FractionField
* DateTime
* Select
* MultiChoice
* MultiSelect
* MultiValue
* Checkbox

Is that correct?

**Comment by xispa** [comment]
> > Something like this should work: ...
> 
> indeed, as a hotfix we added an additional element containing the selected values after line 252 in the `referencesamples.py`, but we used existing method int the class `get_assigned_services_uids`:
> ```python
> item["SupportedServices"] = self.get_assigned_services_uids()
> ```
> and it helped us.
> 

Yep, please open a PR with this change against `senaite.core`

**Comment by xispa** [comment]
> > In fact, what we should do instead is to remove remove these selected = props.selected or @is_selected() spread in React components that don't use them like MultiSelect (assigned [here](https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/TableCell.coffee#L784) , but not used at all when rendering the options [here](https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/MultiSelect.coffee#L128)). They are really confusing. Same with MultiValue component, etc.
> 
> From what I gather from your suggestion and after analyzing the code, it seems that we need to completely remove `selected = props.selected or @is_selected()` and `selected={selected}` in the `TableCell.coffee` component for each field type:
> * CalculatedField
> * NumericField
> * StringField
> * FractionField
> * DateTime
> * Select
> * MultiChoice
> * MultiSelect
> * MultiValue
> * Checkbox
> 
> Is that correct?

Haven't checked throughly, but I would only modify those that expect multiple records (MultiSelect, MultiChoice and MultiValue). Anyhow, this is not critical, don't spend too much time on this.

**Comment by Bugerman58** [comment]
see https://github.com/senaite/senaite.core/pull/2530

**Pull request closed without merging**
